Link do Kaggle:https://www.kaggle.com/datasets/amanarora/obesity-among-adults-by-country-19752016

In [1]:
import pandas as pd
import numpy as np

/home/kira/anaconda3/lib/python3.7/site-packages/setuptools/_importlib.py:42: SetuptoolsWarning: Incompatibility problem.
!!

        ********************************************************************************
        `importlib-metadata` version is incompatible with `setuptools`.
        This problem is likely to be solved by installing an updated version of
        `importlib-metadata`.

        See https://github.com/python/importlib_metadata/issues/396 for details.
        ********************************************************************************

!!
  disable_importlib_metadata_finder(metadata)

# . Limpe os dados do DataFrame,criando uma coluna de nome 'obesity' que conter√° os valores de obesidade.Transforme em float as colunas que porventura foram importadas como string .

In [2]:
df_obesidade = pd.read_csv('obesity-cleaned.csv')

In [3]:
df_obesidade

       Unnamed: 0      Country  Year       Obesity (%)         Sex
0               0  Afghanistan  1975     0.5 [0.2-1.1]  Both sexes
1               1  Afghanistan  1975     0.2 [0.0-0.6]        Male
2               2  Afghanistan  1975     0.8 [0.2-2.0]      Female
3               3  Afghanistan  1976     0.5 [0.2-1.1]  Both sexes
4               4  Afghanistan  1976     0.2 [0.0-0.7]        Male
5               5  Afghanistan  1976     0.8 [0.2-2.0]      Female
6               6  Afghanistan  1977     0.6 [0.2-1.2]  Both sexes
7               7  Afghanistan  1977     0.2 [0.0-0.7]        Male
8               8  Afghanistan  1977     0.9 [0.3-2.1]      Female
9               9  Afghanistan  1978     0.6 [0.2-1.3]  Both sexes
10             10  Afghanistan  1978     0.2 [0.1-0.7]        Male
11             11  Afghanistan  1978     0.9 [0.3-2.2]      Female
12             12  Afghanistan  1979     0.6 [0.3-1.3]  Both sexes
13             13  Afghanistan  1979     0.3 [0.1-0.8]        Male
14             14  Afghanistan  1979     1.0 [0.3-2.3]      Female
15             15  Afghanistan  1980     0.7 [0.3-1.4]  Both sexes
16             16  Afghanistan  1980     0.3 [0.1-0.8]        Male
17             17  Afghanistan  1980     1.1 [0.4-2.4]      Female
18             18  Afghanistan  1981     0.7 [0.3-1.4]  Both sexes
19             19  Afghanistan  1981     0.3 [0.1-0.8]        Male
20             20  Afghanistan  1981     1.1 [0.4-2.5]      Female
21             21  Afghanistan  1982     0.8 [0.4-1.5]  Both sexes
22             22  Afghanistan  1982     0.3 [0.1-0.9]        Male
23             23  Afghanistan  1982     1.2 [0.4-2.6]      Female
24             24  Afghanistan  1983     0.8 [0.4-1.6]  Both sexes
25             25  Afghanistan  1983     0.4 [0.1-0.9]        Male
26             26  Afghanistan  1983     1.3 [0.5-2.7]      Female
27             27  Afghanistan  1984     0.9 [0.4-1.7]  Both sexes
28             28  Afghanistan  1984     0.4 [0.1-1.0]        Male
29             29  Afghanistan  1984     1.4 [0.5-2.9]      Female
...           ...          ...   ...               ...         ...
24540       24540     Zimbabwe  2007  12.9 [10.3-15.8]  Both sexes
24541       24541     Zimbabwe  2007     3.3 [1.9-5.4]        Male
24542       24542     Zimbabwe  2007  21.3 [16.6-26.6]      Female
24543       24543     Zimbabwe  2008  13.2 [10.5-16.1]  Both sexes
24544       24544     Zimbabwe  2008     3.5 [1.9-5.7]        Male
24545       24545     Zimbabwe  2008  21.7 [17.0-27.1]      Female
24546       24546     Zimbabwe  2009  13.5 [10.8-16.5]  Both sexes
24547       24547     Zimbabwe  2009     3.6 [2.0-5.9]        Male
24548       24548     Zimbabwe  2009  22.2 [17.4-27.7]      Female
24549       24549     Zimbabwe  2010  13.8 [11.0-16.8]  Both sexes
24550       24550     Zimbabwe  2010     3.7 [2.1-6.1]        Male
24551       24551     Zimbabwe  2010  22.6 [17.7-28.1]      Female
24552       24552     Zimbabwe  2011  14.1 [11.2-17.2]  Both sexes
24553       24553     Zimbabwe  2011     3.9 [2.1-6.4]        Male
24554       24554     Zimbabwe  2011  23.0 [18.0-28.8]      Female
24555       24555     Zimbabwe  2012  14.3 [11.4-17.6]  Both sexes
24556       24556     Zimbabwe  2012     4.0 [2.2-6.6]        Male
24557       24557     Zimbabwe  2012  23.5 [18.3-29.3]      Female
24558       24558     Zimbabwe  2013  14.6 [11.5-18.0]  Both sexes
24559       24559     Zimbabwe  2013     4.2 [2.3-6.9]        Male
24560       24560     Zimbabwe  2013  23.9 [18.5-30.0]      Female
24561       24561     Zimbabwe  2014  14.9 [11.7-18.4]  Both sexes
24562       24562     Zimbabwe  2014     4.4 [2.4-7.3]        Male
24563       24563     Zimbabwe  2014  24.4 [18.8-30.6]      Female
24564       24564     Zimbabwe  2015  15.2 [11.9-18.8]  Both sexes
24565       24565     Zimbabwe  2015     4.5 [2.4-7.6]        Male
24566       24566     Zimbabwe  2015  24.8 [18.9-31.3]      Female
24567       24567     Zimbabwe  2016  15.5 [12.0-19.2]  Both sexes
24568       24568     Zimbabwe  2016     4.7 [2.5-8.0]        Male
24569       24569     Zimbabwe  2016  25.3 [19.1-32.0]      Female

[24570 rows x 5 columns]

In [4]:
df_obesidade.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24570 entries, 0 to 24569
Data columns (total 5 columns):
Unnamed: 0     24570 non-null int64
Country        24570 non-null object
Year           24570 non-null int64
Obesity (%)    24570 non-null object
Sex            24570 non-null object
dtypes: int64(2), object(3)
memory usage: 959.8+ KB

In [5]:
df_obesidade['Obesity (%)'].iloc[0]

'0.5 [0.2-1.1]'

In [6]:
df_obesidade['Obesity (%)'].value_counts()

No data             504
0.4 [0.1-1.0]        55
0.6 [0.2-1.3]        47
0.3 [0.1-0.8]        46
0.3 [0.1-0.7]        46
0.4 [0.1-0.9]        35
0.5 [0.2-1.1]        35
0.3 [0.1-0.6]        33
0.7 [0.3-1.4]        32
0.6 [0.2-1.4]        32
0.8 [0.3-1.6]        29
0.4 [0.1-1.1]        29
0.9 [0.4-1.7]        29
0.9 [0.4-1.8]        28
1.0 [0.4-2.0]        28
0.7 [0.3-1.5]        28
0.8 [0.3-1.7]        27
0.5 [0.2-1.2]        27
0.3 [0.1-0.9]        26
0.6 [0.2-1.2]        26
0.5 [0.2-1.0]        26
0.2 [0.0-0.7]        25
0.4 [0.1-1.2]        24
1.2 [0.5-2.3]        24
0.2 [0.1-0.5]        23
1.0 [0.5-1.8]        23
0.6 [0.2-1.5]        23
1.1 [0.5-2.0]        22
0.7 [0.3-1.3]        22
0.7 [0.2-1.6]        21
                   ...
8.5 [5.4-12.5]        1
12.6 [9.3-16.4]       1
18.3 [11.5-26.8]      1
19.2 [13.3-25.8]      1
2.2 [1.0-4.3]         1
4.7 [2.9-7.3]         1
20.3 [13.6-28.4]      1
11.9 [10.1-13.8]      1
15.3 [9.5-22.2]       1
5.3 [2.4-9.4]         1
13.7 [9.0-19.3]       1
8.2 [5.1-12.1]        1
7.0 [5.3-8.9]         1
17.7 [12.8-23.0]      1
5.5 [3.3-8.5]         1
17.6 [12.4-23.8]      1
16.2 [11.4-21.8]      1
39.3 [33.5-45.2]      1
12.9 [11.0-14.8]      1
16.8 [10.9-23.6]      1
22.4 [15.7-29.8]      1
45.3 [39.2-51.3]      1
16.2 [12.1-20.8]      1
24.7 [16.4-34.3]      1
6.3 [4.4-8.8]         1
29.7 [27.2-32.2]      1
4.7 [2.0-9.3]         1
38.6 [33.4-44.0]      1
16.7 [11.6-23.0]      1
30.5 [23.9-37.7]      1
Name: Obesity (%), Length: 16375, dtype: int64

In [7]:
df_obesidade.columns

Index(['Unnamed: 0', 'Country', 'Year', 'Obesity (%)', 'Sex'], dtype='object')

In [8]:
del df_obesidade['Unnamed: 0']

In [9]:
df_obesidade['Obesity'] = df_obesidade['Obesity (%)'].apply(lambda x: x.split()[0])

In [10]:
df_obesidade.loc[df_obesidade['Obesity'] == 'No','Obesity'] = np.nan

In [11]:
df_obesidade['Obesity'] = df_obesidade['Obesity'].dropna()

In [12]:
df_obesidade['Obesity'] = df_obesidade['Obesity'].apply(lambda x: float(x))

In [13]:
df_obesidade['Year'] = df_obesidade['Year'].apply(lambda x:int(x))

In [14]:
df_obesidade.set_index("Year", inplace=True)

# .  Qual o procentual m√©dio de obesidade por sexo no mundo no ano de 2015?

In [15]:
df_obesidade[df_obesidade.index == 2015].groupby('Sex').mean()

              Obesity
Sex
Both sexes  19.508377
Female      22.899476
Male        15.980628

# . Quais sao os  paises com a maior e a menor taxa de aumento nos indices de obesidade no periodo observado em 2015?

In [16]:
#087

# . Quais os pa√≠ses com maiores e menores niveis percetuais de obesidade no periodo observado?

# . Quais os paises com maiores e menores niveis percetuais de obesidade em 2015?

# . Qual a diferen√ßa m√©dia percentual de obesidade entre sexos ao longo dos anos para o Brasil?

# . Informe as regioes com maiores crescimentos de PIB per capita no seculo passado.

# . Preecha os anos ausente em cada pais com uma estimativa, baseada na diferen√ßa entre o proximo registrado e o anterior.

# DESAFIOS

# . Voce conseguiria criar um mapa do gdp e da obsesidade no  mundo ao longo dos anos?

# . H√° uma rela√ßao entre niveis de obesidade e gdp per capita